### ISSUE TITLE
可否顺手添加一下clash mate配置

### ISSUE THREAD

**Issue by akaagiao1** [yonggekkk/Tuic-yg#1]
，勇哥摸摸哒

**Comment by yonggekkk** [comment]
> ，勇哥摸摸哒

关键我都没用clash...有官方说明地址吗？

**Comment by akaagiao1** [comment]
就是参考hi，hysteria，一件脚本，在生成v2rayn，配置的同时在顺便生成一份clash.mate的文件，
https://clash-meta.wiki/example，
https://github.com/emptysuns/Hi_Hysteria

**Comment by akaagiao1** [comment]
毕竟opwrt好像就openclash支持

**Comment by yonggekkk** [comment]
> 毕竟opwrt好像就openclash支持

ok

**Comment by yonggekkk** [comment]
已更新
