### ISSUE TITLE
tuic-server-0.8.5-x86_64-linux-gnu 服务器 配置文件客户端模式无法启动 

### ISSUE THREAD

**Issue by ilovebamboo** [yonggekkk/Tuic-yg#13]
tuic-server-0.8.5-x86_64-linux-gnu 

<img width="763" alt="image" src="https://github.com/user-attachments/assets/d6d3f26f-1e85-489b-8bfd-d30676433997">
改了很多次配置文件 是不是不支持？
v2n客户端没问题 
 我用来中转 不行

**Comment by ilovebamboo** [comment]
改了客户c端版本 但是连接反代理 无法通过

**Comment by ilovebamboo** [comment]
{
    "inbounds": [
        {
            "tag": "local-in",
            "type": "socks",
            "listen": "0.0.0.0",
            "port": 1080,
            "settings": {
                "auth": "noauth",
                "udp": true
            }
        }
    ],
    "outbounds": [
        {
            "type": "quic",
            "tag": "quic-out",
            "server": "1.1.1.1",  
            "server_port": 443,  
            "uuid": "c11113f-3618-45e0-884d-5b35f4156ef8", 
            "password": "111", 
            "congestion_control": "bbr",
            "tls": {
                "enabled": true,
                "server_name": "www.bing.com",  
                "insecure": true, 
                "alpn": ["h3"] 
            },
            "udp": true 
        }
    ],
    "log": {
        "level": "debug" 
    }
}
<img width="895" alt="image" src="https://github.com/user-attachments/assets/31d657f5-a7c2-4c5f-9fd7-be4ae1500137">

**Comment by yonggekkk** [comment]
建议使用singbox

**Comment by ilovebamboo** [comment]
> 建议使用singbox

那个不支持quic sing-box 服务器端客户端配置后 访问不行 v2rayn只能win
