### ISSUE TITLE
不同运营商不同设备不同VPS单线程速率均无法突破70Mbps

### ISSUE THREAD

**Issue by wjr050430** [yonggekkk/Tuic-yg#2]
rt，在联通环境和移动环境测试，两台vps为不同地区不同线路的vps，单线程都无法突破70Mbps，是做了什么特殊设置限速以避免QOS还是TUIC自身问题？

**Comment by yonggekkk** [comment]
不清楚了！脚本未做任何限制！建议问下tuic作者
