### ISSUE TITLE
TUIC未更新到最新版本

### ISSUE THREAD

**Issue by TeamBBC12345** [yonggekkk/Tuic-yg#3]
请问可以增加一个选项能更新到pre的版本吗？
比如说现在pre版本是tuic-client-1.0.0-pre-alpha0，但脚本好像只默认正式版v0.8.5为最新版本，谢谢

**Comment by yonggekkk** [comment]
目前仅正式！后续会跟进！！

**Comment by TeamBBC12345** [comment]
大佬，tuic更新到tuic-server-1.0.0正式版了，多了UUID等配置了，等待更新🥹

**Comment by yonggekkk** [comment]
> 大佬，tuic更新到tuic-server-1.0.0正式版了，多了UUID等配置了，等待更新🥹

![photo_2023-06-10_00-01-45](https://github.com/yonggekkk/Tuic-yg/assets/121604513/ce1b161b-5f57-4c62-8904-a5ad97e38803)
试了下，没问题，后续自定义项会增加几个。。再更新吧

**Comment by yonggekkk** [comment]
> 大佬，tuic更新到tuic-server-1.0.0正式版了，多了UUID等配置了，等待更新🥹

已更新支持，点更新即可，如果还是有乱码，可以先卸载原版脚本再更新
